amis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from .views import home, about, faq
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('property/', include('property.urls', namespace='property')),
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('faq/', faq, name='faq'),


    path('admin/', admin.site.urls)
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

property/urls.py
from django.urls import path
from .views import PropertyListView, PropertyDetailView, SellPropertyListView, SellPropertyDetailView


app_name = 'property'

urlpatterns = [
    path('', PropertyListView.as_view(), name='property'),
    path('sell/', SellPropertyListView.as_view(), name='property'),
    path('<slug:slug>/', PropertyDetailView.as_view(), name='property_detail'),
    path('<slug:slug>/', SellPropertyDetailView.as_view(), name='sell_property_detail')
]

property/models.py
from distutils.command.upload import upload
import email
from django.db import models
from django.urls import reverse
from imagekit.models import ImageSpecField
from pilkit.processors import ResizeToFill
from django.utils.text import slugify
import datetime
from django.utils import timezone

Status = (
('For Rent', 'For Rent'),
('For Sale', 'For Sale'),
)

Features = (
('Modern Lawn', 'Modern Lawn'),
('Modern Kitchen', 'Modern Kitchen'),
('Modern Balcony', 'Modern Balcony'),
('Gym Room', 'Gym Room'),
('Servents Room', 'Servents Room'),
('Fire Alarm Available', 'Fire Alarm Available'),
('Swimming Pool', 'Swimming Pool'),
('Modern Laundry', 'Modern Laundry'),
('Pets Box', 'Pets Box'),
('4 Cars Space', '4 Cars Space'),
('New drawing Room', 'New drawing Room'),
('Games Room', 'Games Room'),
('Elevator', 'Elevator'),
('Beautiful Gardens', 'Beautiful Gardens'),
('Basketball court', 'Basketball court'),
)

State = (
('FC' , 'Abuja'),
('AB' , 'Abia'),
('AD' , 'Adamawa'),
('AK' , 'Akwa Ibom'),
('AN' , 'Anambra'),
('BA' , 'Bauchi'),
('BY' , 'Bayelsa'),
('BE' , 'Benue'),
('BO' , 'Borno'),
('CR' , 'Cross River'),
('DE' , 'Delta'),
('EB' , 'Ebonyi'),
('ED' , 'Edo'),
('EK' , 'Ekiti'),
('EN' , 'Enugu'),
('GO' , 'Gombe'),
('IM' , 'Imo'),
('JI' , 'Jigawa'),
('KD' , 'Kaduna'),
('KN' , 'Kano'),
('KT' , 'Katsina'),
('KE' , 'Kebbi'),
('KO' , 'Kogi'),
('KW' , 'Kwara'),
('LA' , 'Lagos'),
('NA' , 'Nassarawa'),
('NI' , 'Niger'),
('OG' , 'Ogun'),
('ON' , 'Ondo'),
('OS' , 'Osun'),
('OY' , 'Oyo'),
('PL' , 'Plateau'),
('RI' , 'Rivers'),
('SO' , 'Sokoto'),
('TA' , 'Taraba'),
('YO' , 'Yobe'),
('ZA' , 'Zamfara'),
)

class Features(models.Model):
    feature_name = models.CharField(max_length=250, choices=Features)

    def __str__(self):
        return self.feature_name


class Property(models.Model):
    city = models.CharField(max_length=250, choices=State)
    address = models.TextField(blank=True, default='')
    bedroom = models.IntegerField()
    bathroom = models.IntegerField()
    washroom = models.IntegerField()
    carSpace = models.IntegerField()
    roomArea = models.IntegerField(blank=True, default='')
    price = models.FloatField()
    availability = models.BooleanField()
    status = models.CharField(max_length=250, choices=Status, default='')
    description = models.IntegerField()
    agent = models.CharField(max_length=200, blank=True)
    features = models.ManyToManyField(to=Features, default='')
    video = models.CharField(max_length=250)
    category = models.CharField(max_length=250)
    createdDate = models.DateTimeField(default=timezone.now)
    updatedDate = models.DateTimeField(default=timezone.now)
    propertyType = models.CharField(max_length=250)
    state =  models.CharField(max_length=250, choices=State)
    postalCode = models.CharField(max_length=250)
    propertyName = models.CharField(max_length=250)
    otherImages = models.FileField(default='')
    image = models.ImageField(upload_to="img")
    image_thumbnail = ImageSpecField(source='image',
                                     processors=[ResizeToFill(549, 376)],
                                     format='JPEG',
                                     options={'quality': 95})
    slug = models.SlugField(max_length=200, db_index=True, default='')

    def __str__(self):
        return self.propertyName

    def save(self, *args, **kwargs):
        value = self.propertyName
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('property:property_detail', args={self.slug})

property/forms.py
# from django import forms
# from .models import Workshop, Delegate, CalenderRegistration, Exhibition, Quiz, PrimaryCompetition

# class WorkshopForm(forms.ModelForm):
#     class Meta:
#         model = Workshop
#         fields = ['workshop_name', 'school', 'delegate']

#     def __init__(self, *args, **kwargs):
#         super(WorkshopForm, self).__init__(*args, **kwargs)
#         for field in self.fields:
#             self.fields[field].widget.attrs['class'] = 'form-control my-2'


# class DelegateForm(forms.ModelForm):
#     class Meta:
#         model = Delegate
#         fields = ['name', 'status_in_school', 'phone_number']

#     def __init__(self, *args, **kwargs):
#         super(DelegateForm, self).__init__(*args, **kwargs)
#         for field in self.fields:
#             self.fields[field].widget.attrs['class'] = 'form-control my-2'

# class CalenderRegForm(forms.ModelForm):
#     class Meta:
#         model = CalenderRegistration
#         fields = '__all__'

#     def __init__(self, *args, **kwargs):
#         super(CalenderRegForm, self).__init__(*args, **kwargs)
#         for field in self.fields:
#             self.fields[field].widget.attrs['class'] = 'form-control my-2'


# class PrimaryCompetitionRegForm(forms.ModelForm):
#     class Meta:
#         model = PrimaryCompetition
#         fields = '__all__'

#     def __init__(self, *args, **kwargs):
#         super(PrimaryCompetitionRegForm, self).__init__(*args, **kwargs)
#         for field in self.fields:
#             self.fields[field].widget.attrs['class'] = 'form-control my-2'

amis/views.py
from django.shortcuts import render
from property.models import Property


def home(request):
    return render(request, 'index.html', {})

def about(request):
    return render(request, 'about.html', {})

def faq(request):
    return render(request, 'faq.html', {})

property/views.py
from .models import Property
from django.views.generic import ListView, DetailView

class PropertyListView(ListView):
    model = Property
    template_name = 'property_list.html'
    context_object_name = 'property_list'
    paginate_by = 10


class PropertyDetailView(DetailView):
    model = Property
    template_name = 'property_detail.html'
    context_object_name = 'property_detail'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the blogs
        context['latest_posts'] = Property.objects.all()[:5]
        return context


class SellPropertyListView(ListView):
    model = Property
    template_name = 'sell_property_list.html'
    context_object_name = 'sell_property_list'
    paginate_by = 10


class SellPropertyDetailView(DetailView):
    model = Property
    template_name = 'sell_property_detail.html'
    context_object_name = 'sell_property_detail'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the blogs
        context['latest_posts'] = Property.objects.all()[:5]

        return context

amis/templates/about.html
{% load static %}
{% include "header.html"  %}
{% block body %}

<section class="services-section alternate">
		<div class="auto-container">
			<!-- Sec Title -->
			<div class="sec-title centered text-center">
				<h1>Our Services</h1>
				<div class="separator"></div>
			</div>
			<div class="row clearfix">
				
				<!-- Services Block -->
				<div class="services-block col-lg-4 col-md-6 col-sm-12">
					<div class="inner-box wow fadeInLeft" data-wow-delay="0ms" data-wow-duration="1500ms">
						<div class="border-one"></div>
						<div class="border-two"></div>
						<div class="icon-box">
							<span class="icon flaticon-house-1"></span>
						</div>
						<h4><a href="take-tour.html">Rent a home</a></h4>
						<div class="text">Secure a good shelter at affordable price.</div>
					</div>
				</div>
				
				<!-- Services Block -->
				<div class="services-block col-lg-4 col-md-6 col-sm-12">
					<div class="inner-box wow fadeInUp" data-wow-delay="250ms" data-wow-duration="1500ms">
						<div class="border-one"></div>
						<div class="border-two"></div>
						<div class="icon-box">
							<span class="icon flaticon-desk"></span>
						</div>
						<h4><a href="take-tour.html">Sell a home</a></h4>
						<div class="text">Sell a home without stress and good rates.</div>
					</div>
				</div>
				
				<!-- Services Block -->
				<div class="services-block col-lg-4 col-md-6 col-sm-12">
					<div class="inner-box wow fadeInRight" data-wow-delay="500ms" data-wow-duration="1500ms">
						<div class="border-one"></div>
						<div class="border-two"></div>
						<div class="icon-box">
							<span class="icon flaticon-house-4"></span>
						</div>
						<h4><a href="take-tour.html">Buy a Home</a></h4>
						<div class="text">Locate and Purchase a home easily with us.</div>
					</div>
				</div>
				
				<!-- Services Block -->
				<div class="services-block col-lg-4 col-md-6 col-sm-12">
					<div class="inner-box wow fadeInLeft" data-wow-delay="0ms" data-wow-duration="1500ms">
						<div class="border-one"></div>
						<div class="border-two"></div>
						<div class="icon-box">
							<span class="icon flaticon-house-search"></span>
						</div>
						<h4><a href="take-tour.html">Buy a Land</a></h4>
						<div class="text">Become a land owner at ease.</div>
					</div>
				</div>
				
				<!-- Services Block -->
				<div class="services-block col-lg-4 col-md-6 col-sm-12">
					<div class="inner-box wow fadeInUp" data-wow-delay="0ms" data-wow-duration="1500ms">
						<div class="border-one"></div>
						<div class="border-two"></div>
						<div class="icon-box">
							<span class="icon flaticon-sofa"></span>
						</div>
						<h4><a href="take-tour.html">Luxury Houses</a></h4>
						<div class="text">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</div>
					</div>
				</div>
				
				<!-- Services Block -->
				<div class="services-block col-lg-4 col-md-6 col-sm-12">
					<div class="inner-box wow fadeInRight" data-wow-delay="0ms" data-wow-duration="1500ms">
						<div class="border-one"></div>
						<div class="border-two"></div>
						<div class="icon-box">
							<span class="icon flaticon-house-4"></span>
						</div>
						<h4><a href="take-tour.html">Renting or Selling</a></h4>
						<div class="text">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</div>
					</div>
				</div>
				
			</div>
		</div>
	</section>


 {% endblock %}

{% include 'footer.html' %}

amis/templates/faq.html
{% include  "header.html" %}
{% block body %}
    <section class="faq-page-section">
    	<div class="auto-container">
			
        	<!--Sec Title-->
            <div class="sec-title centered">
            	<h1>Faq's</h1>
                <div class="separator"></div>
            </div>
			
			<div class="masonry-items-container row clearfix">
				<!--Faq Block-->
				<div class="faq-block masonry-item col-lg-4 col-md-6 col-sm-12">
					<div class="question"><h4>How can you contact us ?</h4></div>
					<div class="answer">
						<p>Lorem ipsum dolor sit amet, consectetuer  a the adipiscing elit. Aenean commodo ligulai dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient.</p>
					</div>
				</div>
				
				<!--Faq Block-->
				<div class="faq-block masonry-item col-lg-4 col-md-6 col-sm-12">
					<div class="question"><h4>How can we reached at you for our services ?</h4></div>
					<div class="answer">
						<p>Lorem ipsum dolor sit amet, consectetuer  a the adipiscing elit. Aenean commodo ligulai dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient Cum sociis natoque penatibus et magnis dis parturient.</p>
					</div>
				</div>
				
				<!--Faq Block-->
				<div class="faq-block masonry-item col-lg-4 col-md-6 col-sm-12">
					<div class="question"><h4>Dream Property - Real Estate  service all over the world ?</h4></div>
					<div class="answer">
						<p>Lorem ipsum dolor sit amet, consectetuer  a the adipiscing elit. Aenean commodo ligulai dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient.</p>
					</div>
				</div>
				
				<!--Faq Block-->
				<div class="faq-block masonry-item col-lg-4 col-md-6 col-sm-12">
					<div class="question"><h4>There is No Fraud in Dream Property - Real Estate  ?</h4></div>
					<div class="answer">
						<p>Lorem ipsum dolor sit amet, consectetuer  a the adipiscing elit. Aenean commodo ligulai dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient.</p>
					</div>
				</div>
				
				<!--Faq Block-->
				<div class="faq-block masonry-item col-lg-4 col-md-6 col-sm-12">
					<div class="question"><h4>100% clients Satisfactions ?</h4></div>
					<div class="answer">
						<p>Lorem ipsum dolor sit amet, consectetuer  a the adipiscing elit. Aenean commodo ligulai dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient.</p>
					</div>
				</div>
				
				<!--Faq Block-->
				<div class="faq-block masonry-item col-lg-4 col-md-6 col-sm-12">
					<div class="question"><h4>If you find problem than quoted ?</h4></div>
					<div class="answer">
						<p>Lorem ipsum dolor sit amet, consectetuer  a the adipiscing elit. Aenean commodo ligulai dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient.</p>
					</div>
				</div>
				
				<!--Faq Block-->
				<div class="faq-block masonry-item col-lg-4 col-md-6 col-sm-12">
					<div class="question"><h4>How can you contact us ?</h4></div>
					<div class="answer">
						<p>Lorem ipsum dolor sit amet, consectetuer  a the adipiscing elit. Aenean commodo ligulai dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient.</p>
					</div>
				</div>
				
				<!--Faq Block-->
				<div class="faq-block masonry-item col-lg-4 col-md-6 col-sm-12">
					<div class="question"><h4>How can we reached at you for our services ?</h4></div>
					<div class="answer">
						<p>Lorem ipsum dolor sit amet, consectetuer  a the adipiscing elit. Aenean commodo ligulai dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient Cum sociis natoque penatibus et magnis dis parturient.</p>
					</div>
				</div>
				
				<!--Faq Block-->
				<div class="faq-block masonry-item col-lg-4 col-md-6 col-sm-12">
					<div class="question"><h4>Dream Property - Real Estate  service all over the world ?</h4></div>
					<div class="answer">
						<p>Lorem ipsum dolor sit amet, consectetuer  a the adipiscing elit. Aenean commodo ligulai dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient.</p>
					</div>
				</div>
				
				<!--Faq Block-->
				<div class="faq-block masonry-item col-lg-4 col-md-6 col-sm-12">
					<div class="question"><h4>There is No Fraud in Dream Property - Real Estate  ?</h4></div>
					<div class="answer">
						<p>Lorem ipsum dolor sit amet, consectetuer  a the adipiscing elit. Aenean commodo ligulai dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient.</p>
					</div>
				</div>
				
				<!--Faq Block-->
				<div class="faq-block masonry-item col-lg-4 col-md-6 col-sm-12">
					<div class="question"><h4>100% clients Satisfactions ?</h4></div>
					<div class="answer">
						<p>Lorem ipsum dolor sit amet, consectetuer  a the adipiscing elit. Aenean commodo ligulai dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient.</p>
					</div>
				</div>
				
				<!--Faq Block-->
				<div class="faq-block masonry-item col-lg-4 col-md-6 col-sm-12">
					<div class="question"><h4>If you find problem than quoted ?</h4></div>
					<div class="answer">
						<p>Lorem ipsum dolor sit amet, consectetuer  a the adipiscing elit. Aenean commodo ligulai dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient.</p>
					</div>
				</div>
				
			</div>
            
        </div>
    </section>
{% endblock %}	

amis/templates/property_detail.html
{% load static %}
{% include "header.html" %}
	<!-- Sidebar Page Container -->
    <div class="sidebar-page-container">
    	<div class="auto-container">
        	<div class="row clearfix">
				<!--Content Side-->
                <div class="content-side col-lg-8 col-md-12 col-sm-12">
					<div class="properties-detail">
						<div class="inner-box">
							<h1>{{property_detail.propertyName}} {{property_detail.id}}</h1>
							<div class="location">{{property_detail.address}}</div>
							<!-- Property List -->
							<ul class="property-list">
								<li>Price :#{{property_detail.price}}</li>
								<li>City :{{property_detail.get_city_display }}</li>
								<li>Bedroom :{{property_detail.bedroom}}</li>
								<li>Bathroom :{{property_detail.bathroom}}</li>
								<li>Car Space :{{property_detail.carSpace}}</li>
								<li>State :{{property_detail.get_city_display }}</li>
								<li>Category :{{property_detail.category}}</li>
								<li>Property Type :{{property_detail.propertyType}}</li>
							</ul>
								<p><a href="https://wa.me/09017219046" class="theme-btn btn-style-one">Contact Agent</a></p>
							<!-- Property Gallery Box -->
							<div class="property-gallery-box">
								<div class="carousel-outer">
									<ul class="image-carousel owl-carousel owl-theme">
										<li><a href="{{property_detail.image_thumbnail.url}}" class="lightbox-image" title="Image Caption Here"><img src="{{property_detail.image_thumbnail.url}}" alt="property image"></a></li>

									</ul>
									
									<ul class="thumbs-carousel owl-carousel owl-theme">
										
									</ul>
								</div>
							</div>
							
							<!-- Property Detail Box -->
							<div class="property-detail-box">
								<h2>Property Details.</h2>
								<div class="text">
									<p>{{property_detail.Description}}</p>
									<ul class="property-info clearfix">
										<li><i class="flaticon-design-tool"></i></li>
										<li><i class="flaticon-bed"></i>{{property_detail.bedroom}} Bedrooms</li>
										<li><i class="flaticon-garage-1"></i>{{property_detail.carSpace}} Garage</li>
										<li><i class="flaticon-shower"></i>{{property_detail.bathroom}} Bathroom</li>
										<li><i class="flaticon-dimension"></i>Price: #{{property_detail.price}}</li>
										<li><i class="flaticon-gallery"></i> City: {{property_detail.city}}</li>
									</ul>
								</div>
								<!-- Property Featured Box -->

								<!-- Video Outer Box -->
								<div class="video-outer-box">
									<h3>Video View</h3>
									<!--Video Box-->
									<div class="video-box">
										<div class="image">
											<a href="{{property_detail.video}}" class="lightbox-image overlay-box"><span class="flaticon-play-button"><i class="ripple"></i></span></a>
											<img src="{% static 'assets/images/background/2.jpg' %}" alt="">
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!--Sidebar Side-->
                <div class="sidebar-side col-lg-4 col-md-12 col-sm-12">
                	<aside class="sidebar sticky-top">
						<div class="sidebar-inner">
						<!-- Social Widget -->
						<div class="sidebar-widget sidebar-social-widget">
							<ul class="social-icon-two">
								<li><a href="https://www.facebook.com/profile.php?id=100081599105741&mibextid=LQQJ4d"><span class="fab fa-facebook-f"></span></a></li>
								<li class="twitter"><a href="https://www.tiktok.com/@hollisstarr"><span class="fab fa-twitter"></span></a></li>
							</ul>
						</div>
						<!-- End Social Widget -->
						
						</div>
					</aside>
				</div>
				
			</div>
		</div>
	</div>

{% include 'footer.html' %}

amis/templates/property_list.html
{% load static %}
		{% include "header.html" %}
		<!-- Search Home Section -->
	
	<!-- End Search Home Section -->
		<!-- Properties Page Section -->
		<section class="properties-page-section">
			<div class="auto-container">
				<div class="row clearfix">
					<!-- Property Block --->
					{% for property in property_list %}
					{% if property.status == "For Rent" %}
				<li>{{property_detail.property_set.all}}</li>
					<div class="property-block col-lg-4 col-md-6 col-sm-12">
						<div class="inner-box">
							<div class="upper-box clearfix">
								<div class="pull-left">
									<div class="price">#{{property.price}}</div>
								</div>
								<div class="pull-right">
									<a class="read-more" href="{{property.get_absolute_url}}">Read More <span
											class="fas fa-angle-double-right"></span></a>
								</div>
							</div>
							<div class="image">
								<span class="featured">featured</span>
								<a href="{{property.get_absolute_url}}"><img src="{{property.image_thumbnail.url}}" alt="" class="resize" /></a>
								<div class="overlay-box">
									<li>House For {{property.status}}</li>
									<li>{{property.availability}}</li>
								</div>
							</div>
							<div class="lower-content">
								<h3><a href="{{property.get_absolute_url}}">{{property.propertyName}}</a></h3>
								<ul class="property-info clearfix">
									<li><i class="flaticon-design-tool"></i>{{property.state}} State</li>
									<li><i class="flaticon-bed"></i> {{property.bedroom}} Bedrooms</li>
									<li><i class="flaticon-garage-1"></i> {{property.carSpace}} Garage</li>
									<li><i class="flaticon-shower"></i> {{property.bathroom}} Bathroom</li>
								</ul>
							</div>
						</div>
					</div>
					{% endif %}
					{% endfor %}
				</div>

				<!-- Styled Pagination 
				<div class="styled-pagination text-center">
					<ul class="inner-container clearfix">
						<li class="prev"><a href="#" class="active"><i class="flaticon-left-arrow"></i> Prev</a></li>
						<li><a href="#">1</a></li>
						<li><a href="#">2</a></li>
						<li class="active"><a href="#">3</a></li>
						<li><a href="#">4</a></li>
						<li><a href="#">5</a></li>
						<li class="next"><a href="#" class="active">Next <i class="flaticon-right-arrow-1"></i></a></li>
					</ul>
				</div>
				-->
			</div>
		</section>
		<!-- End Team Section -->

{% include 'footer.html' %}

amis/templates/sell_property_detail.html
{% load static %}
{% include "header.html" %}
	<!-- Sidebar Page Container -->
    <div class="sidebar-page-container">
    	<div class="auto-container">
        	<div class="row clearfix">
				<!--Content Side-->
                <div class="content-side col-lg-8 col-md-12 col-sm-12">
					<div class="properties-detail">
						<div class="inner-box">
							<h1>{{property_detail.propertyName}} {{property_detail.id}}</h1>
							<div class="location">{{property_detail.address}}</div>
							<!-- Property List -->
							<ul class="property-list">
								<li>Price :#{{property_detail.price}}</li>
								<li>City :{{property_detail.get_city_display }}</li>
								<li>Bedroom :{{property_detail.bedroom}}</li>
								<li>Bathroom :{{property_detail.bathroom}}</li>
								<li>Car Space :{{property_detail.carSpace}}</li>
								<li>State :{{property_detail.get_city_display }}</li>
								<li>Category :{{property_detail.category}}</li>
								<li>Property Type :{{property_detail.propertyType}}</li>
							</ul>
								<p><a href="https://wa.me/09017219046" class="theme-btn btn-style-one">Contact Agent</a></p>
							<!-- Property Gallery Box -->
							<div class="property-gallery-box">
								
								<div class="carousel-outer">
									<ul class="image-carousel owl-carousel owl-theme">
										<li><a href="{{property_detail.image_thumbnail.url}}" class="lightbox-image" title="Image Caption Here"><img src="{{property_detail.image_thumbnail.url}}" alt="property image"></a></li>
									</ul>
									
									<ul class="thumbs-carousel owl-carousel owl-theme">
									
									</ul>
								</div>
							
							</div>
							
							<!-- Property Detail Box -->
							<div class="property-detail-box">
								<h2>Property Details.</h2>
								<div class="text">
									<p>{{property_detail.Description}}</p>
									<ul class="property-info clearfix">
										<li><i class="flaticon-design-tool"></i></li>
										<li><i class="flaticon-bed"></i>{{property_detail.bedroom}} Bedrooms</li>
										<li><i class="flaticon-garage-1"></i>{{property_detail.carSpace}} Garage</li>
										<li><i class="flaticon-shower"></i>{{property_detail.bathroom}} Bathroom</li>
										<li><i class="flaticon-dimension"></i>Price: #{{property_detail.price}}</li>
										<li><i class="flaticon-gallery"></i> City: {{property_detail.city}}</li>
									</ul>
								</div>
								<!-- Property Featured Box -->
								


								<!-- Video Outer Box -->
								<div class="video-outer-box">
									<h3>Video View</h3>
									<!--Video Box-->
									<div class="video-box">
										<div class="image">
											<a href="{{property_detail.video}}" class="lightbox-image overlay-box"><span class="flaticon-play-button"><i class="ripple"></i></span></a>
											<img src="assets/images/background/2.jpg" alt="">
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!--Sidebar Side-->
                <div class="sidebar-side col-lg-4 col-md-12 col-sm-12">
                	<aside class="sidebar sticky-top">
						<div class="sidebar-inner">
						<!-- Social Widget -->
						<div class="sidebar-widget sidebar-social-widget">
							<ul class="social-icon-two">
								<li><a href="https://www.facebook.com/profile.php?id=100081599105741&mibextid=LQQJ4d"><span class="fab fa-facebook-f"></span></a></li>
								<li class="twitter"><a href="https://www.tiktok.com/@hollisstarr"><span class="fab fa-twitter"></span></a></li>
							</ul>
						</div>
						<!-- End Social Widget -->
						
						</div>
					</aside>
				</div>
				
			</div>
		</div>
	</div>

{% include 'footer.html' %}